[package]
name = "arkworks-keccak"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-381 = "0.4"
ark-ff = "0.4"
ark-r1cs-std = "0.4"
ark-relations = "0.4"
ark-std = "0.4"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }

